[project]
name = "mcp-add-notes"
version = "0.1.0"
description = "mcp for adding notes locally"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=25.1.0",
    "fastapi[standard]>=0.128.5",
    "fastmcp>=2.14.5",
    "python-dotenv>=1.0.0",
]
